//Get tileset to load Check
//get data to load    Check
//Design Charts in Illustrator
//Set up Title and background image
//

//Sources:
//https://carsonnow.org/story/07/14/2015/waterfall-fire-began-11-years-ago-today
//https://www.bozemandailychronicle.com/news/county/one-year-later-bridger-foothills-fire-stirs-feelings-of-loss-appreciation/article_47c21952-4bd7-55cf-9b0c-692ccc347d20.html
//https://www.nfpa.org//-/media/Files/Firewise/Fact-sheets/FirewiseHowToPrepareYourHomeForWildfires.pdf
//https://wildfiretoday.com/2020/11/17/lawsuit-filed-to-obtain-documents-about-the-beachie-creek-fire-in-oregon/
